main = "src/worker.ts"
name = "proxy"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 10018

[[durable_objects.bindings]]
name = "MyClass"
class_name = "MyClass"

[[migrations]]
tag = "v1"
new_classes = ["DurableProxy"]
